name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://doublecuts.ru
    steps:
      - uses: actions/checkout@v3

      - name: Cache Nuxt Build
        uses: actions/cache@v4.0.2
        with:
          path: .nuxt
          key: "${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}"
          restore-keys: "${{ runner.os }}-build-"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: ls -al node_modules && npm install

      - name: Build
        run: ls -al .nuxt && npm run generate

      - name: Clear target directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: rm -rf /www/*

      - name: Archive dist
        run: tar -cvf dist.tar -C dist .

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: dist.tar
          target: /www/

      - name: Unarchive dist
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: >
            cd /www && tar -xvf dist.tar
            && rm dist.tar
            && chown -R root:root /www
